/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddAddressInput {
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'isDefault' : boolean,
  'phone' : string,
  'pincode' : string,
}
export interface Address {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'isDefault' : boolean,
  'phone' : string,
  'pincode' : string,
}
export interface Cart {
  'totalAmount' : bigint,
  'buyerId' : UserId,
  'items' : Array<CartItem>,
}
export interface CartItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'priceAtAdd' : bigint,
}
export type Category = { 'groceries' : null } |
  { 'others' : null } |
  { 'clothes' : null } |
  { 'books' : null } |
  { 'essentials' : null } |
  { 'electronics' : null };
export interface CreateProductInput {
  'deliveryEstimate' : string,
  'title' : string,
  'description' : string,
  'stock' : bigint,
  'currency' : string,
  'category' : Category,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface DeliveryAddress {
  'city' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
  'pincode' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'total' : bigint,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'estimatedDelivery' : string,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'sellerId' : UserId,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'title' : string,
  'productId' : ProductId,
  'quantity' : bigint,
  'priceAtOrder' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null };
export interface PlaceOrderInput {
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'items' : Array<{ 'productId' : ProductId, 'quantity' : bigint }>,
}
export interface Product {
  'id' : ProductId,
  'deliveryEstimate' : string,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'stock' : bigint,
  'currency' : string,
  'category' : Category,
  'sellerId' : UserId,
  'rating' : number,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductFilter {
  'minRating' : [] | [number],
  'inStockOnly' : boolean,
  'maxPrice' : [] | [bigint],
  'category' : [] | [Category],
  'keyword' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ProductId = bigint;
export interface SaveProfileInput {
  'displayName' : string,
  'role' : UserRole,
  'phone' : string,
}
export type Timestamp = bigint;
export interface UpdateCartItemInput {
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface UpdateProductInput {
  'id' : ProductId,
  'deliveryEstimate' : string,
  'title' : string,
  'description' : string,
  'isActive' : boolean,
  'stock' : bigint,
  'currency' : string,
  'category' : Category,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'displayName' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'updatedAt' : Timestamp,
  'addresses' : Array<Address>,
  'phone' : string,
}
export type UserRole = { 'seller' : null } |
  { 'buyer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAddress' : ActorMethod<[AddAddressInput], Address>,
  'addToCart' : ActorMethod<[ProductId, bigint], Cart>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelOrder' : ActorMethod<[OrderId], Order>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<[CreateProductInput], Product>,
  'deleteAddress' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCart' : ActorMethod<[], Cart>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMySellerOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyProducts' : ActorMethod<[], Array<Product>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'placeOrder' : ActorMethod<[PlaceOrderInput], Array<Order>>,
  'removeFromCart' : ActorMethod<[ProductId], Cart>,
  'reorder' : ActorMethod<[OrderId], Cart>,
  'saveCallerUserProfile' : ActorMethod<[SaveProfileInput], undefined>,
  'setDefaultAddress' : ActorMethod<[bigint], undefined>,
  'updateAddress' : ActorMethod<[bigint, AddAddressInput], Address>,
  'updateCartItem' : ActorMethod<[UpdateCartItemInput], Cart>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], Order>,
  'updateProduct' : ActorMethod<[UpdateProductInput], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];