/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddAddressInput = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const Address = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'isDefault' : IDL.Bool,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const ProductId = IDL.Nat;
export const UserId = IDL.Principal;
export const CartItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceAtAdd' : IDL.Nat,
});
export const Cart = IDL.Record({
  'totalAmount' : IDL.Nat,
  'buyerId' : UserId,
  'items' : IDL.Vec(CartItem),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const DeliveryAddress = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const OrderItem = IDL.Record({
  'title' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'priceAtOrder' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'total' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'estimatedDelivery' : IDL.Text,
  'updatedAt' : Timestamp,
  'buyerId' : UserId,
  'sellerId' : UserId,
  'items' : IDL.Vec(OrderItem),
});
export const Category = IDL.Variant({
  'groceries' : IDL.Null,
  'others' : IDL.Null,
  'clothes' : IDL.Null,
  'books' : IDL.Null,
  'essentials' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateProductInput = IDL.Record({
  'deliveryEstimate' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'currency' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'deliveryEstimate' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'stock' : IDL.Nat,
  'currency' : IDL.Text,
  'category' : Category,
  'sellerId' : UserId,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'seller' : IDL.Null,
  'buyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'updatedAt' : Timestamp,
  'addresses' : IDL.Vec(Address),
  'phone' : IDL.Text,
});
export const ProductFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'inStockOnly' : IDL.Bool,
  'maxPrice' : IDL.Opt(IDL.Nat),
  'category' : IDL.Opt(Category),
  'keyword' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const PlaceOrderInput = IDL.Record({
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'items' : IDL.Vec(
    IDL.Record({ 'productId' : ProductId, 'quantity' : IDL.Nat })
  ),
});
export const SaveProfileInput = IDL.Record({
  'displayName' : IDL.Text,
  'role' : UserRole,
  'phone' : IDL.Text,
});
export const UpdateCartItemInput = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UpdateProductInput = IDL.Record({
  'id' : ProductId,
  'deliveryEstimate' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat,
  'currency' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAddress' : IDL.Func([AddAddressInput], [Address], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [Cart], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelOrder' : IDL.Func([OrderId], [Order], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func([CreateProductInput], [Product], []),
  'deleteAddress' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMySellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderInput], [IDL.Vec(Order)], []),
  'removeFromCart' : IDL.Func([ProductId], [Cart], []),
  'reorder' : IDL.Func([OrderId], [Cart], []),
  'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
  'setDefaultAddress' : IDL.Func([IDL.Nat], [], []),
  'updateAddress' : IDL.Func([IDL.Nat, AddAddressInput], [Address], []),
  'updateCartItem' : IDL.Func([UpdateCartItemInput], [Cart], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [Order], []),
  'updateProduct' : IDL.Func([UpdateProductInput], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddAddressInput = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const Address = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'isDefault' : IDL.Bool,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const ProductId = IDL.Nat;
  const UserId = IDL.Principal;
  const CartItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceAtAdd' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'totalAmount' : IDL.Nat,
    'buyerId' : UserId,
    'items' : IDL.Vec(CartItem),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const DeliveryAddress = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const OrderItem = IDL.Record({
    'title' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'priceAtOrder' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'total' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Timestamp,
    'estimatedDelivery' : IDL.Text,
    'updatedAt' : Timestamp,
    'buyerId' : UserId,
    'sellerId' : UserId,
    'items' : IDL.Vec(OrderItem),
  });
  const Category = IDL.Variant({
    'groceries' : IDL.Null,
    'others' : IDL.Null,
    'clothes' : IDL.Null,
    'books' : IDL.Null,
    'essentials' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateProductInput = IDL.Record({
    'deliveryEstimate' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'currency' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'deliveryEstimate' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'stock' : IDL.Nat,
    'currency' : IDL.Text,
    'category' : Category,
    'sellerId' : UserId,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({ 'seller' : IDL.Null, 'buyer' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'updatedAt' : Timestamp,
    'addresses' : IDL.Vec(Address),
    'phone' : IDL.Text,
  });
  const ProductFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'inStockOnly' : IDL.Bool,
    'maxPrice' : IDL.Opt(IDL.Nat),
    'category' : IDL.Opt(Category),
    'keyword' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const PlaceOrderInput = IDL.Record({
    'deliveryAddress' : DeliveryAddress,
    'paymentMethod' : PaymentMethod,
    'items' : IDL.Vec(
      IDL.Record({ 'productId' : ProductId, 'quantity' : IDL.Nat })
    ),
  });
  const SaveProfileInput = IDL.Record({
    'displayName' : IDL.Text,
    'role' : UserRole,
    'phone' : IDL.Text,
  });
  const UpdateCartItemInput = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UpdateProductInput = IDL.Record({
    'id' : ProductId,
    'deliveryEstimate' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat,
    'currency' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAddress' : IDL.Func([AddAddressInput], [Address], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [Cart], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelOrder' : IDL.Func([OrderId], [Order], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func([CreateProductInput], [Product], []),
    'deleteAddress' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMySellerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderInput], [IDL.Vec(Order)], []),
    'removeFromCart' : IDL.Func([ProductId], [Cart], []),
    'reorder' : IDL.Func([OrderId], [Cart], []),
    'saveCallerUserProfile' : IDL.Func([SaveProfileInput], [], []),
    'setDefaultAddress' : IDL.Func([IDL.Nat], [], []),
    'updateAddress' : IDL.Func([IDL.Nat, AddAddressInput], [Address], []),
    'updateCartItem' : IDL.Func([UpdateCartItemInput], [Cart], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [Order], []),
    'updateProduct' : IDL.Func([UpdateProductInput], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };