/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: ProductId;
    deliveryEstimate: string;
    title: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    stock: bigint;
    currency: string;
    category: Category;
    sellerId: UserId;
    rating: number;
    price: bigint;
    images: Array<ExternalBlob>;
}
export interface UserProfile {
    id: UserId;
    displayName: string;
    createdAt: Timestamp;
    role: UserRole;
    updatedAt: Timestamp;
    addresses: Array<Address>;
    phone: string;
}
export type Timestamp = bigint;
export interface OrderItem {
    title: string;
    productId: ProductId;
    quantity: bigint;
    priceAtOrder: bigint;
}
export interface UpdateProductInput {
    id: ProductId;
    deliveryEstimate: string;
    title: string;
    description: string;
    isActive: boolean;
    stock: bigint;
    currency: string;
    category: Category;
    price: bigint;
    images: Array<ExternalBlob>;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Cart {
    totalAmount: bigint;
    buyerId: UserId;
    items: Array<CartItem>;
}
export interface DeliveryAddress {
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
    phone: string;
    pincode: string;
}
export interface AddAddressInput {
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
    isDefault: boolean;
    phone: string;
    pincode: string;
}
export interface SaveProfileInput {
    displayName: string;
    role: UserRole;
    phone: string;
}
export interface PlaceOrderInput {
    deliveryAddress: DeliveryAddress;
    paymentMethod: PaymentMethod;
    items: Array<{
        productId: ProductId;
        quantity: bigint;
    }>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UpdateCartItemInput {
    productId: ProductId;
    quantity: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: DeliveryAddress;
    total: bigint;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    estimatedDelivery: string;
    updatedAt: Timestamp;
    buyerId: UserId;
    sellerId: UserId;
    items: Array<OrderItem>;
}
export interface ProductFilter {
    minRating?: number;
    inStockOnly: boolean;
    maxPrice?: bigint;
    category?: Category;
    keyword?: string;
    minPrice?: bigint;
}
export interface CreateProductInput {
    deliveryEstimate: string;
    title: string;
    description: string;
    stock: bigint;
    currency: string;
    category: Category;
    price: bigint;
    images: Array<ExternalBlob>;
}
export type UserId = Principal;
export type ProductId = bigint;
export interface CartItem {
    productId: ProductId;
    quantity: bigint;
    priceAtAdd: bigint;
}
export type OrderId = bigint;
export interface Address {
    id: bigint;
    city: string;
    name: string;
    state: string;
    addressLine1: string;
    addressLine2: string;
    isDefault: boolean;
    phone: string;
    pincode: string;
}
export enum Category {
    groceries = "groceries",
    others = "others",
    clothes = "clothes",
    books = "books",
    essentials = "essentials",
    electronics = "electronics"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    upi = "upi",
    cashOnDelivery = "cashOnDelivery",
    card = "card"
}
export enum UserRole {
    seller = "seller",
    buyer = "buyer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addAddress(input: AddAddressInput): Promise<Address>;
    addToCart(productId: ProductId, quantity: bigint): Promise<Cart>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelOrder(orderId: OrderId): Promise<Order>;
    clearCart(): Promise<void>;
    createProduct(input: CreateProductInput): Promise<Product>;
    deleteAddress(addressId: bigint): Promise<void>;
    deleteProduct(productId: ProductId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getCart(): Promise<Cart>;
    getMyOrders(): Promise<Array<Order>>;
    getMySellerOrders(): Promise<Array<Order>>;
    getOrder(orderId: OrderId): Promise<Order | null>;
    getProduct(productId: ProductId): Promise<Product | null>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listMyProducts(): Promise<Array<Product>>;
    listProducts(filterOpts: ProductFilter): Promise<Array<Product>>;
    placeOrder(input: PlaceOrderInput): Promise<Array<Order>>;
    removeFromCart(productId: ProductId): Promise<Cart>;
    reorder(orderId: OrderId): Promise<Cart>;
    saveCallerUserProfile(input: SaveProfileInput): Promise<void>;
    setDefaultAddress(addressId: bigint): Promise<void>;
    updateAddress(addressId: bigint, input: AddAddressInput): Promise<Address>;
    updateCartItem(input: UpdateCartItemInput): Promise<Cart>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<Order>;
    updateProduct(input: UpdateProductInput): Promise<Product>;
}
import type { Address as _Address, Category as _Category, CreateProductInput as _CreateProductInput, DeliveryAddress as _DeliveryAddress, ExternalBlob as _ExternalBlob, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PlaceOrderInput as _PlaceOrderInput, Product as _Product, ProductFilter as _ProductFilter, ProductId as _ProductId, SaveProfileInput as _SaveProfileInput, Timestamp as _Timestamp, UpdateProductInput as _UpdateProductInput, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addAddress(arg0: AddAddressInput): Promise<Address> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(arg0);
            return result;
        }
    }
    async addToCart(arg0: ProductId, arg1: bigint): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: OrderId): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return from_candid_Order_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return from_candid_Order_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createProduct(arg0: CreateProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(await to_candid_CreateProductInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(await to_candid_CreateProductInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAddress(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddress(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySellerOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySellerOrders();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySellerOrders();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyProducts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyProducts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: PlaceOrderInput): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n41(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n41(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: ProductId): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async reorder(arg0: OrderId): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.reorder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorder(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: SaveProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_SaveProfileInput_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_SaveProfileInput_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setDefaultAddress(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultAddress(arg0);
            return result;
        }
    }
    async updateAddress(arg0: bigint, arg1: AddAddressInput): Promise<Address> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddress(arg0, arg1);
            return result;
        }
    }
    async updateCartItem(arg0: UpdateCartItemInput): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Order_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Order_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: UpdateProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_UpdateProductInput_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_UpdateProductInput_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n10(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    deliveryAddress: _DeliveryAddress;
    total: bigint;
    paymentMethod: _PaymentMethod;
    createdAt: _Timestamp;
    estimatedDelivery: string;
    updatedAt: _Timestamp;
    buyerId: _UserId;
    sellerId: _UserId;
    items: Array<_OrderItem>;
}): {
    id: OrderId;
    status: OrderStatus;
    deliveryAddress: DeliveryAddress;
    total: bigint;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    estimatedDelivery: string;
    updatedAt: Timestamp;
    buyerId: UserId;
    sellerId: UserId;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n12(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n14(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        estimatedDelivery: value.estimatedDelivery,
        updatedAt: value.updatedAt,
        buyerId: value.buyerId,
        sellerId: value.sellerId,
        items: value.items
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    deliveryEstimate: string;
    title: string;
    createdAt: _Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    stock: bigint;
    currency: string;
    category: _Category;
    sellerId: _UserId;
    rating: number;
    price: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ProductId;
    deliveryEstimate: string;
    title: string;
    createdAt: Timestamp;
    description: string;
    isActive: boolean;
    updatedAt: Timestamp;
    stock: bigint;
    currency: string;
    category: Category;
    sellerId: UserId;
    rating: number;
    price: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        deliveryEstimate: value.deliveryEstimate,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        stock: value.stock,
        currency: value.currency,
        category: from_candid_Category_n24(_uploadFile, _downloadFile, value.category),
        sellerId: value.sellerId,
        rating: value.rating,
        price: value.price,
        images: await from_candid_vec_n26(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    displayName: string;
    createdAt: _Timestamp;
    role: _UserRole;
    updatedAt: _Timestamp;
    addresses: Array<_Address>;
    phone: string;
}): {
    id: UserId;
    displayName: string;
    createdAt: Timestamp;
    role: UserRole;
    updatedAt: Timestamp;
    addresses: Array<Address>;
    phone: string;
} {
    return {
        id: value.id,
        displayName: value.displayName,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n31(_uploadFile, _downloadFile, value.role),
        updatedAt: value.updatedAt,
        addresses: value.addresses,
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "outForDelivery" in value ? OrderStatus.outForDelivery : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cashOnDelivery: null;
} | {
    card: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cashOnDelivery" in value ? PaymentMethod.cashOnDelivery : "card" in value ? PaymentMethod.card : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    groceries: null;
} | {
    others: null;
} | {
    clothes: null;
} | {
    books: null;
} | {
    essentials: null;
} | {
    electronics: null;
}): Category {
    return "groceries" in value ? Category.groceries : "others" in value ? Category.others : "clothes" in value ? Category.clothes : "books" in value ? Category.books : "essentials" in value ? Category.essentials : "electronics" in value ? Category.electronics : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seller: null;
} | {
    buyer: null;
}): UserRole {
    return "seller" in value ? UserRole.seller : "buyer" in value ? UserRole.buyer : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n10(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n22(_uploadFile, _downloadFile, x)));
}
function to_candid_Category_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateProductInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductInput): Promise<_CreateProductInput> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderInput_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderInput): _PlaceOrderInput {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_SaveProfileInput_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveProfileInput): _SaveProfileInput {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateProductInput_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductInput): Promise<_UpdateProductInput> {
    return await to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryEstimate: string;
    title: string;
    description: string;
    stock: bigint;
    currency: string;
    category: Category;
    price: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    deliveryEstimate: string;
    title: string;
    description: string;
    stock: bigint;
    currency: string;
    category: _Category;
    price: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        deliveryEstimate: value.deliveryEstimate,
        title: value.title,
        description: value.description,
        stock: value.stock,
        currency: value.currency,
        category: to_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        price: value.price,
        images: await to_candid_vec_n20(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: number;
    inStockOnly: boolean;
    maxPrice?: bigint;
    category?: Category;
    keyword?: string;
    minPrice?: bigint;
}): {
    minRating: [] | [number];
    inStockOnly: boolean;
    maxPrice: [] | [bigint];
    category: [] | [_Category];
    keyword: [] | [string];
    minPrice: [] | [bigint];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        inStockOnly: value.inStockOnly,
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n18(_uploadFile, _downloadFile, value.category)) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deliveryAddress: DeliveryAddress;
    paymentMethod: PaymentMethod;
    items: Array<{
        productId: ProductId;
        quantity: bigint;
    }>;
}): {
    deliveryAddress: _DeliveryAddress;
    paymentMethod: _PaymentMethod;
    items: Array<{
        productId: _ProductId;
        quantity: bigint;
    }>;
} {
    return {
        deliveryAddress: value.deliveryAddress,
        paymentMethod: to_candid_PaymentMethod_n43(_uploadFile, _downloadFile, value.paymentMethod),
        items: value.items
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    role: UserRole;
    phone: string;
}): {
    displayName: string;
    role: _UserRole;
    phone: string;
} {
    return {
        displayName: value.displayName,
        role: to_candid_UserRole_n47(_uploadFile, _downloadFile, value.role),
        phone: value.phone
    };
}
async function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    deliveryEstimate: string;
    title: string;
    description: string;
    isActive: boolean;
    stock: bigint;
    currency: string;
    category: Category;
    price: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    id: _ProductId;
    deliveryEstimate: string;
    title: string;
    description: string;
    isActive: boolean;
    stock: bigint;
    currency: string;
    category: _Category;
    price: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        deliveryEstimate: value.deliveryEstimate,
        title: value.title,
        description: value.description,
        isActive: value.isActive,
        stock: value.stock,
        currency: value.currency,
        category: to_candid_Category_n18(_uploadFile, _downloadFile, value.category),
        price: value.price,
        images: await to_candid_vec_n20(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    groceries: null;
} | {
    others: null;
} | {
    clothes: null;
} | {
    books: null;
} | {
    essentials: null;
} | {
    electronics: null;
} {
    return value == Category.groceries ? {
        groceries: null
    } : value == Category.others ? {
        others: null
    } : value == Category.clothes ? {
        clothes: null
    } : value == Category.books ? {
        books: null
    } : value == Category.essentials ? {
        essentials: null
    } : value == Category.electronics ? {
        electronics: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cashOnDelivery: null;
} | {
    card: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cashOnDelivery ? {
        cashOnDelivery: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    seller: null;
} | {
    buyer: null;
} {
    return value == UserRole.seller ? {
        seller: null
    } : value == UserRole.buyer ? {
        buyer: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n21(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
